version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - ">= 0"
  - dependency-name: electron-settings
    versions:
    - ">= 0"
  - dependency-name: less
    versions:
    - ">= 0"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-i18next
    versions:
    - 11.8.5
  - dependency-name: i18next
    versions:
    - 19.8.4
  - dependency-name: wd
    versions:
    - 1.13.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
